"""
Dofus 3 game tables -> game/data (read by shared/game_data.gd).

    python gamedata.py experience        # game/data/experience.json: total XP to reach each level
    python gamedata.py shops dofus               # game/worlds/dofus/shops.json: what the real merchants sell (+ their items)
    python gamedata.py interactives incarnam   # game/worlds/incarnam/interactives.json (harvestable elements) + tables skills, jobs
    python gamedata.py quests incarnam   # game/worlds/incarnam/quests.json (after npcs, before items)
    python gamedata.py items incarnam    # game/data/items.json: the items the monsters of a world drop
                                         # + their icons in Content/Picto/Items/<icon>.webp
    python gamedata.py items incarnam            # game/data/items.json: the world's drops + EXTRA_ITEMS, with effects
    python gamedata.py table breeds [--fields id,maleLook] [--ids 1,2]
                                         # game/data/tables/breeds.json: a light copy of a table
                                         # (GameData.table("breeds") reads it before the raw content)

maps.py world runs both after writing a world.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import UnityPy

sys.path.insert(0, str(Path(__file__).parent))
from extract import DEFAULT_GAME, Extractor, detect_unity_version  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
CONTENT = ROOT / "game" / "content" / "Content"
DATA = ROOT / "game" / "data"
MAX_LEVEL = 200
# Server data absent from the Dofus 3 client (the skin a worn hat / cape / shield
# adds to the look): the JondoEmu emulator dumps (https://github.com/julianout/JondoEmu,
# no license: read locally, never republished). equipment_skins.json: `skins` item id ->
# skin id; 286 measured on captures of a real server, `_inferred` matched by image
# (100 % on the measured ones), `_inferred_needs_review` unreliable (left out).
from jondo import JONDO_DATOS  # noqa: E402


def _table(name: str) -> dict:
    path = CONTENT / "Data" / f"{name}.json"
    if not path.exists():
        UnityPy.config.FALLBACK_UNITY_VERSION = detect_unity_version(DEFAULT_GAME)
        Extractor(DEFAULT_GAME, CONTENT.parent, "webp").data(name)
    return json.loads(path.read_text(encoding="utf-8"))["objectsById"]


def experience() -> None:
    xp = _table("characterxpmappingsdataroot")
    levels = [int(xp[str(lv)]["experiencePoints"]) for lv in range(1, MAX_LEVEL + 1)]
    (DATA / "experience.json").write_text(json.dumps({
        "_doc": "Generated by tools/extractor/gamedata.py (Dofus 3 characterxpmappings): levels[i] = total XP of level i+1.",
        "levels": levels}), encoding="utf-8")
    print(f"  experience: {len(levels)} levels -> {DATA / 'experience.json'}")


# P1.05: items every world gets (no shop yet): Incarnam bread, healing potions, recall
# potion, characteristic scrolls; and two Incarnam equipments whose effects are rolled
EXTRA_ITEMS = [468, 536, 1182, 1183, 10792, 548, 683, 795, 802, 803, 806, 807, 809, 811, 2473, 44,
               # P1.06: the Panoplie du Jeune Aventurier, a ring, a Dofus, a shield, conditional items
               2474, 2475, 2476, 2477, 2478, 852, 7113, 7097, 758, 6679,
               # P1.10: Michette (effect 139, +30 energy)
               521,
               # P1.06b: the Intrépide hat, cape and shield (level 1, skins measured in JondoEmu)
               10801, 10800, 10798]
RUNE_TYPE = 78  # itemtypes.id of the forgemagie runes
WEAPON_FIELDS = {"apCost": "ap", "minRange": "min_range", "range": "range", "criticalHitProbability": "crit",
                 "criticalHitBonus": "crit_bonus", "castInLine": "in_line", "castTestLos": "los",
                 "maxCastPerTurn": "per_turn"}


def items(world: str, shops_only: bool = False) -> None:
    sys.path.insert(0, str(Path(__file__).parent))
    from spells import i18n_reader
    text = i18n_reader(CONTENT / "I18n" / "fr.bin")
    ids = set()
    folder = ROOT / "game" / "worlds" / world
    for f in ([] if shops_only else (folder / "maps").glob("*.json")):  # hand-made worlds: fixed groups
        for g in json.loads(f.read_text(encoding="utf-8")).get("groups", []):
            for m in g.get("members", []):
                ids.update(int(d["item"]) for d in m.get("drops", []))
    if (folder / "monsters.json").exists() and not shops_only:  # real worlds: the drops of every grade
        for mo in json.loads((folder / "monsters.json").read_text(encoding="utf-8"))["monsters"].values():
            for m in mo["grades"]:
                ids.update(int(d["item"]) for d in m.get("drops", []))
    if not shops_only:
        ids.update(EXTRA_ITEMS)
    if (folder / "shops.json").exists():  # P2.02: what the NPCs of the world sell
        for sh in json.loads((folder / "shops.json").read_text(encoding="utf-8"))["shops"].values():
            ids.update(int(i) for i in sh["items"])
    if (folder / "quests.json").exists():  # P2.03: the items quests give / ask for
        for q in json.loads((folder / "quests.json").read_text(encoding="utf-8"))["quests"].values():
            for st in q["steps"]:
                ids.update(int(o["params"][1]) for o in st["objectives"] if o["type"] in (2, 3) and len(o["params"]) > 1)
                ids.update(int(o["params"][0]) for o in st["objectives"] if o["type"] in (8, 17))
                ids.update(int(i[0]) for r in st["rewards"] for i in r["items"])
    # P2.07: the forgemagie runes (items of type 78), kept whole
    ids.update(int(k) for k, v in _table("itemsdataroot").items() if int(v.get("typeId", 0)) == RUNE_TYPE)
    path = DATA / "items.json"
    known = {int(i["id"]): i for i in json.loads(path.read_text(encoding="utf-8"))["items"]} if path.exists() else {}
    table = _table("itemsdataroot")
    skins = equipment_skins()
    for i in sorted(ids):
        it = table.get(str(i))
        if it:
            known[i] = {"id": i, "name_id": int(it["nameId"]), "name": text(it["nameId"]), "icon": int(it["iconId"]),
                        "type": int(it["typeId"]), "level": int(it["level"]), "weight": int(it.get("realWeight", 1)),
                        # P2.02: items.price (kamas), the NPC sell price; the buy-back price is derived (NpcShop)
                        "price": int(it.get("price", 0)),
                        "description_id": int(it.get("descriptionId", 0)),
                        # m_flags bit 0: usable (set on every consumable, never on resources / equipment)
                        "usable": bool(int(it.get("m_flags", 0)) & 1), "criteria": it.get("criterions", ""),
                        # possibleEffects: [effects.id, diceNum, diceSide, value]
                        "effects": [[int(e["effectId"]), int(e["diceNum"]), int(e["diceSide"]), int(e["value"])]
                                    for e in it.get("possibleEffects", [])]}
            if int(it.get("itemSetId", -1)) > 0:
                known[i]["set"] = int(it["itemSetId"])
            if i in skins:  # the skin it adds to the look when worn (LookBuilder.with_equipment)
                known[i]["skin"], known[i]["skin_src"] = skins[i]
            if "apCost" in it:  # a weapon: how its hit is cast
                known[i]["weapon"] = {out: int(it[k]) for k, out in WEAPON_FIELDS.items() if k in it}
    # the item sets of these items: itemsets.effects[n - 1] = the bonus for n items worn
    sets_table = _table("itemsetsdataroot")
    sets = []
    for sid in sorted({v["set"] for v in known.values() if "set" in v}):
        st = sets_table[str(sid)]
        sets.append({"id": sid, "name_id": int(st["nameId"]), "items": [int(x) for x in st["items"]],
                     "effects": [[[int(e["effectId"]), int(e["diceNum"]), int(e["diceSide"]), int(e["value"])]
                                  for e in (b["values"] if isinstance(b, dict) else b)] for b in st["effects"]]})
    path.write_text(json.dumps({"_doc": "Generated by tools/extractor/gamedata.py items <world>. See shared/game_data.gd.",
                                "items": sorted(known.values(), key=lambda x: x["id"]), "sets": sets}, indent="\t", ensure_ascii=False),
                    encoding="utf-8")
    print(f"  items: {len(known)} -> {path}")
    icons(sorted({int(v["icon"]) for v in known.values()}))


def shops(world: str) -> None:
    """P2.02: what the NPC merchants sell (JondoEmu npc_shops.json, from the real server: npc id -> item ids) for the
    NPCs placed in the world (npcs.json) -> game/worlds/<world>/shops.json, then the items they sell (items.json, with
    their icons). A world with no real merchant keeps its (hand-written) shops.json."""
    src = JONDO_DATOS / "npc_shops.json"
    if not src.exists():
        sys.exit(f"no {src}: shop contents are server data, absent from the client")
    folder = ROOT / "game" / "worlds" / world
    placed = {int(n["npc"]) for v in json.loads((folder / "npcs.json").read_text(encoding="utf-8"))["maps"].values() for n in v}
    sold = {k: sorted(set(int(i) for i in v)) for k, v in json.loads(src.read_text(encoding="utf-8"))["npcs"].items() if int(k) in placed}
    if not sold:
        print(f"  shops: no merchant placed in {world}: {folder / 'shops.json'} untouched")
        return
    (folder / "shops.json").write_text(json.dumps({"_doc": "Generated by tools/extractor/gamedata.py shops <world>: what the NPC merchants sell (JondoEmu npc_shops.json, server data, no licence: do not republish). Key = npcs.id, items = items.id sold at items.price.",
                                                   "shops": {k: {"items": v} for k, v in sorted(sold.items(), key=lambda kv: int(kv[0]))}},
                                                  separators=(",", ":")), encoding="utf-8")
    print(f"  shops: {len(sold)} merchants, {sum(len(v) for v in sold.values())} offers -> {folder / 'shops.json'}")
    items(world, shops_only=True)


def equipment_skins() -> dict[int, tuple[int, str]]:
    """item id -> (skin id, "measured" | "inferred") from JondoEmu, {} without the dumps."""
    path = JONDO_DATOS / "equipment_skins.json"
    if not path.exists():
        print(f"  ! no {path}: worn items keep the bare look", file=sys.stderr)
        return {}
    d = json.loads(path.read_text(encoding="utf-8"))
    review = set(d.get("_inferred_needs_review", []))
    inferred = set(d.get("_inferred", []))
    return {int(k): (int(v), "inferred" if int(k) in inferred else "measured")
            for k, v in d.get("skins", {}).items() if int(k) not in review}


# cell 559 (the last one) is where the dump parks elements that are not on the grid (hidden, no position)
OFF_GRID = 559


def interactives(world: str) -> None:
    """P2.05: the harvestable elements of the maps of a world -> game/worlds/<world>/interactives.json
    {maps: {map id: [{e: element id, cell, gfx, skill: skills.id}]}}. Which elements stand where is a client
    data (ClientInteractiveElementTransform: id, cell, gfx), but the skill an element offers is server data:
    JondoEmu interactive_elements.json (elements per map) and recursos_*.json (gfx -> skill, measured on captures
    of a real server, crossed with skills.gatheredRessourceItem). Graphics whose capture contradicted itself
    (`discrepa`: shared by several types, e.g. gfx 1018 is not only a fishing spot) are left out."""
    elements = JONDO_DATOS / "interactive_elements.json"
    resources = next(iter(sorted(JONDO_DATOS.glob("recursos_*.json"))), None)
    if not elements.exists() or resources is None:
        sys.exit(f"no {elements} / recursos_*.json: harvestable elements are server data")
    gfx_skill = {int(g): int(v["habilidad"]) for g, v in json.loads(resources.read_text(encoding="utf-8"))["recursos"].items()
                 if not v.get("discrepa")}
    folder = ROOT / "game" / "worlds" / world
    have = {f.stem for f in (folder / "maps").glob("*.json")}
    out: dict[str, list] = {}
    for map_id, els in json.loads(elements.read_text(encoding="utf-8")).items():
        if map_id not in have:
            continue
        found = [{"e": int(e["e"]), "cell": int(e["c"]), "gfx": int(e["g"]), "skill": gfx_skill[int(e["g"])]}
                 for e in els if int(e["g"]) in gfx_skill and int(e["c"]) != OFF_GRID]
        if found:
            out[map_id] = sorted(found, key=lambda x: x["e"])
    (folder / "interactives.json").write_text(json.dumps({"_doc": "Generated by tools/extractor/gamedata.py interactives <world>: harvestable elements (JondoEmu interactive_elements.json + recursos_*.json, server data, no licence: do not republish).",
                                                         "maps": out}, separators=(",", ":")), encoding="utf-8")
    print(f"  interactives: {sum(len(v) for v in out.values())} elements on {len(out)} maps -> {folder / 'interactives.json'}")
    derive("skills", ["id", "nameId", "parentJobId", "gatheredRessourceItem", "range", "useAnimation", "cursor", "levelMin", "isForgemagus", "modifiableItemTypeIds"])
    derive("jobs")


def derive(name: str, fields: list[str] | None = None, ids: list[str] | None = None) -> None:
    """Copies (part of) a raw table into game/data/tables, which ships with the
    game: the sim and the server must not depend on game/content (never
    committed, hundreds of MB)."""
    table = _table(name if name.endswith("dataroot") else name + "dataroot")
    short = name.removesuffix("dataroot")
    rows = {k: v for k, v in table.items() if not ids or k in ids}
    if fields:
        rows = {k: {f: v[f] for f in fields if f in v} for k, v in rows.items()}
    for row in rows.values():
        row.pop("m_flags", None)
    out = DATA / "tables" / f"{short}.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps({"_doc": f"Generated by tools/extractor/gamedata.py table {short} (Dofus 3 {short}dataroot).",
                               "objectsById": rows}, separators=(",", ":"), ensure_ascii=False), encoding="utf-8")
    print(f"  table {short}: {len(rows)} rows -> {out}")


def npcs(world: str) -> None:
    """P2.01: where the NPCs stand (JondoEmu npcs_reales.json: the server's own declarations, cell and facing,
    swept from real captures) -> game/worlds/<world>/npcs.json, and the light `npcs` table of the templates
    placed (game/data/tables/npcs.json: look, name id, dialog message / reply text ids, actions)."""
    src = JONDO_DATOS / "npcs_reales.json"
    if not src.exists():
        sys.exit(f"no {src}: NPC positions are server data, absent from the client")
    folder = ROOT / "game" / "worlds" / world
    have = {int(f.stem) for f in (folder / "maps").glob("*.json")}
    placed: dict[str, list] = {}
    for n in json.loads(src.read_text(encoding="utf-8"))["npcs"]:
        if int(n["mapa"]) in have:
            placed.setdefault(str(n["mapa"]), []).append({"npc": int(n["npc"]), "cell": int(n["casilla"]), "dir": int(n["orientacion"])})
    (folder / "npcs.json").write_text(json.dumps({"_doc": "Generated by tools/extractor/gamedata.py npcs <world>: NPC positions of the real server (JondoEmu npcs_reales.json, no licence: do not republish).",
                                                  "maps": placed}, separators=(",", ":")), encoding="utf-8")
    ids = sorted({n["npc"] for v in placed.values() for n in v})
    print(f"  npcs: {sum(len(v) for v in placed.values())} on {len(placed)} maps, {len(ids)} templates -> {folder / 'npcs.json'}")
    path = DATA / "tables" / "npcs.json"
    kept = {}
    if path.exists():  # several worlds share the table: keep what the others placed
        kept = json.loads(path.read_text(encoding="utf-8"))["objectsById"]
    table = _table("npcsdataroot")
    fields = ["id", "nameId", "dialogMessages", "dialogReplies", "actions", "gender", "look"]
    for i in ids:
        if str(i) in table:
            kept[str(i)] = {f: table[str(i)][f] for f in fields if f in table[str(i)]}
    path.write_text(json.dumps({"_doc": "Generated by tools/extractor/gamedata.py npcs <world> (Dofus 3 npcsdataroot, the templates placed in a world).",
                                "objectsById": dict(sorted(kept.items(), key=lambda kv: int(kv[0])))}, separators=(",", ":"), ensure_ascii=False), encoding="utf-8")
    print(f"  table npcs: {len(kept)} rows -> {path}")


QUEST_TYPES = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 14, 16, 17}  # objective types the sim can follow (QuestEngine)


def _objective_args(t: int, p: list[int], names: dict) -> list:
    """What the client puts in #1 #2 #3 of an objective type's text (questobjectivetypes.nameId): {"t": i18n id} or {"n": number}."""
    def tid(kind: str, i: int) -> dict:
        return {"t": int(names[kind].get(str(i), {}).get("nameId", 0))}
    n = lambda i: {"n": int(p[i]) if len(p) > i else 0}  # noqa: E731
    if t in (0, 4):
        return [{"t": p[0]}]
    if t in (2, 3):
        return [tid("npcs", p[0]), tid("items", p[1]), n(2)]
    if t in (1, 9):
        return [tid("npcs", p[0])]
    if t == 5:
        return [tid("subareas", p[0])]
    if t in (6, 14):
        return [tid("monsters", p[0]), n(1)]
    if t == 16:
        return [tid("monsters", p[0]), n(1), {"t": p[4] if len(p) > 4 else 0}]
    if t == 7:
        return [tid("monsters", p[0])]
    if t == 8:
        return [tid("items", p[0])]
    if t == 17:
        return [tid("items", p[0]), n(1)]
    return []


def _quest_cell(blocked: set[int], exits: set[int], used: list[int]) -> int:
    """A cell for an NPC the client data places on a map without saying where: the walkable cell closest to the middle of the map,
    at least 3 cells from the others (cell ids run along a row of 14: 280 is about the centre)."""
    for c in sorted(range(0, 560), key=lambda c: (abs(c - 280), c)):
        if c in blocked or c in exits or any(abs(c - u) < 3 for u in used):
            continue
        return c
    return 280


def quests(world: str) -> None:
    """P2.03: the quests a world can play -> game/worlds/<world>/quests.json (compact: quests -> steps -> objectives, rewards)
    from the Dofus 3 tables quests / queststeps / questobjectives / queststeprewards. A quest is kept when its start NPC
    (quests.startPosition) stands on a map of the world and every objective is of a type the sim follows (QUEST_TYPES) and on a map of the world.
    The NPCs of the quests (start, talk-to, hand-in) that npcs.json does not place get a cell (APPROX(P2.03): the client gives
    the map of an NPC, never the cell; the JondoEmu list places only a few) and their template joins the npcs table.
    Run after `npcs <world>` (which rewrites npcs.json), then `items <world>` for the items."""
    folder = ROOT / "game" / "worlds" / world
    have = {int(f.stem) for f in (folder / "maps").glob("*.json")}
    q_t, s_t, o_t, r_t = (_table(n) for n in ("questsdataroot", "queststepsdataroot", "questobjectivesdataroot", "queststeprewardsdataroot"))
    names = {"npcs": _table("npcsdataroot"), "items": _table("itemsdataroot"), "monsters": _table("monstersdataroot"),
             "subareas": _table("subareasdataroot")}
    out: dict[str, dict] = {}
    for q in q_t.values():
        start = next((p for p in q["startPosition"] if int(p["mapId"]) in have and str(p["npcId"]) in names["npcs"]), None)
        if start is None or q["isEvent"] or not q["stepIds"]:
            continue
        steps, ok = [], True
        for sid in q["stepIds"]:
            st = s_t.get(str(sid))
            if st is None:
                ok = False
                break
            objs = []
            for oid in st["objectiveIds"]:
                o = o_t[str(oid)]
                if int(o["typeId"]) not in QUEST_TYPES or (int(o["mapId"]) != 0 and int(o["mapId"]) not in have):
                    ok = False  # an objective the world cannot offer (a type the sim ignores, a map it does not have)
                    break
                if int(o["typeId"]) in (1, 2, 3, 9) and str(o["parameters"]["parameter0"]) not in names["npcs"]:
                    ok = False  # an NPC with no template cannot be placed
                    break
                n = max(int(o["parameters"]["numParams"]), 1)
                params = [int(o["parameters"][f"parameter{i}"]) for i in range(5 if int(o["typeId"]) == 16 else n)]
                objs.append({"id": int(o["id"]), "type": int(o["typeId"]), "map": int(o["mapId"]), "params": params,
                             "args": _objective_args(int(o["typeId"]), params, names)})
            if not ok or not objs:
                ok = False
                break
            rewards = []
            for rid in st["rewardsIds"]:
                r = r_t[str(rid)]
                rewards.append({"level_min": int(r["levelMin"]), "level_max": int(r["levelMax"]), "xp": float(r["experienceRatio"]),
                                "kamas": float(r["kamasRatio"]), "scale": int(r["kamasScaleWithPlayerLevel"]),
                                "items": [[int(i["values"][0]), int(i["values"][1])] for i in r["itemsReward"]],
                                "emotes": [int(e) for e in r["emotesReward"]], "spells": [int(e) for e in r["spellsReward"]],
                                "titles": [int(e) for e in r["titlesReward"]],
                                "jobs": [int(e) for e in r["jobsReward"]]})
            steps.append({"id": int(st["id"]), "name_id": int(st["nameId"]), "desc_id": int(st["descriptionId"]),
                          "level": int(st["optimalLevel"]), "objectives": objs, "rewards": rewards})
        if ok:
            out[str(q["id"])] = {"id": int(q["id"]), "name_id": int(q["nameId"]), "category": int(q["categoryId"]),
                                 "level_min": int(q["levelMin"]), "level_max": int(q["levelMax"]), "criteria": q["startCriterion"],
                                 "repeat": int(q["repeatType"]), "start": {"npc": int(start["npcId"]), "map": int(start["mapId"])},
                                 "steps": steps}
    (folder / "quests.json").write_text(json.dumps({"_doc": "Generated by tools/extractor/gamedata.py quests <world> (Dofus 3 quests tables). Server data absent: the dialogs of the steps.",
                                                    "quests": out}, separators=(",", ":")), encoding="utf-8")
    print(f"  quests: {len(out)} -> {folder / 'quests.json'}")
    # the NPCs the quests talk to
    wanted: dict[int, set[int]] = {}  # map -> npc ids
    for q in out.values():
        wanted.setdefault(q["start"]["map"], set()).add(q["start"]["npc"])
        for st in q["steps"]:
            for o in st["objectives"]:
                if o["type"] in (1, 2, 3, 9) and o["map"] in have:
                    wanted.setdefault(o["map"], set()).add(o["params"][0])
    path = folder / "npcs.json"
    doc = json.loads(path.read_text(encoding="utf-8")) if path.exists() else {"maps": {}}
    maps = doc.setdefault("maps", {})
    for m, lst in maps.items():  # a previous run's guesses go
        maps[m] = [n for n in lst if not n.get("approx")]
    placed = {(int(m), n["npc"]) for m, lst in maps.items() for n in lst}  # (map, npc template)
    table = _table("npcsdataroot")
    added = 0
    for m, ids in sorted(wanted.items()):
        info = json.loads((folder / "maps" / f"{m}.json").read_text(encoding="utf-8"))
        blocked, exits = set(info.get("blocked", [])), {int(c) for c in info.get("map_change", {})}
        lst = maps.setdefault(str(m), [])
        used = [int(n["cell"]) for n in lst]
        for npc in sorted(ids):
            if (m, npc) in placed or str(npc) not in table:
                continue
            c = _quest_cell(blocked, exits, used)
            used.append(c)
            lst.append({"npc": npc, "cell": c, "dir": 1, "approx": True})
            placed.add((m, npc))
            added += 1
    doc["maps"] = {m: lst for m, lst in maps.items() if lst}
    path.write_text(json.dumps(doc, separators=(",", ":")), encoding="utf-8")
    tpath = DATA / "tables" / "npcs.json"
    kept = json.loads(tpath.read_text(encoding="utf-8"))["objectsById"] if tpath.exists() else {}
    for i in {npc for _, npc in placed}:
        if str(i) in table:
            kept[str(i)] = {f: table[str(i)][f] for f in ["id", "nameId", "dialogMessages", "dialogReplies", "actions", "gender", "look"] if f in table[str(i)]}
    tpath.write_text(json.dumps({"_doc": "Generated by tools/extractor/gamedata.py npcs <world> (Dofus 3 npcsdataroot, the templates placed in a world).",
                                 "objectsById": dict(sorted(kept.items(), key=lambda kv: int(kv[0])))}, separators=(",", ":"), ensure_ascii=False), encoding="utf-8")
    print(f"  quest NPCs placed by guess: {added}")


def icons(icon_ids: list[int]) -> None:
    out = CONTENT / "Picto" / "Items"
    out.mkdir(parents=True, exist_ok=True)
    wanted = {str(i) for i in icon_ids if not (out / f"{i}.webp").exists()}
    if not wanted:
        return
    UnityPy.config.FALLBACK_UNITY_VERSION = detect_unity_version(DEFAULT_GAME)
    env = UnityPy.load(str(DEFAULT_GAME / "Dofus_Data/StreamingAssets/Content/Picto/Items/item_assets_1x.bundle"))
    n = 0
    for o in env.objects:
        if o.type.name == "Sprite" and o.peek_name() in wanted:
            o.read().image.save(out / f"{o.peek_name()}.webp", lossless=True, quality=0, method=0, exact=True)
            n += 1
    print(f"  item icons: {n}/{len(wanted)}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("experience")
    i = sub.add_parser("items")
    i.add_argument("world")
    t = sub.add_parser("table")
    t.add_argument("name")
    t.add_argument("--fields", help="comma-separated fields to keep (default: all)")
    t.add_argument("--ids", help="comma-separated row ids to keep (default: all)")
    n = sub.add_parser("npcs")
    n.add_argument("world")
    sh = sub.add_parser("shops")
    sh.add_argument("world")
    qs = sub.add_parser("quests")
    qs.add_argument("world")
    ia = sub.add_parser("interactives")
    ia.add_argument("world")
    args = ap.parse_args()
    if args.cmd == "interactives":
        interactives(args.world)
    elif args.cmd == "quests":
        quests(args.world)
    elif args.cmd == "npcs":
        npcs(args.world)
    elif args.cmd == "shops":
        shops(args.world)
    elif args.cmd == "experience":
        experience()
    elif args.cmd == "table":
        split = lambda v: [x.strip() for x in v.split(",") if x.strip()] if v else None  # noqa: E731
        derive(args.name, split(args.fields), split(args.ids))
    else:
        items(args.world)


if __name__ == "__main__":
    main()
