## What the player reads for each Protocol error code.
class_name ErrorTexts
extends RefCounted

const TEXTS := {
	Protocol.E_BAD_MESSAGE: "Commande invalide",
	Protocol.E_VERSION: "Version du jeu incompatible avec le serveur",
	Protocol.E_BAD_CREDENTIALS: "Identifiant ou mot de passe incorrect",
	Protocol.E_LOGIN_TAKEN: "Cet identifiant est déjà pris",
	Protocol.E_BAD_LOGIN: "Identifiant : 3 à 24 caractères (a-z, 0-9, _ ou -) ; mot de passe : 6 caractères au moins",
	Protocol.E_ALREADY_CONNECTED: "Ce compte est déjà connecté",
	Protocol.E_NOT_LOGGED_IN: "Connectez-vous d'abord",
	Protocol.E_REGISTRATION_CLOSED: "Ce serveur ne crée pas de nouveaux comptes",
	Protocol.E_TOO_MANY_ATTEMPTS: "Trop d'essais : reconnectez-vous plus tard",
	Protocol.E_NETWORK: "Connexion au serveur perdue ou impossible",
	Protocol.E_UNKNOWN_WORLD: "Ce monde n'existe pas",
	Protocol.E_UNKNOWN_COMMAND: "Action impossible",
	Protocol.E_CONNECTED_ELSEWHERE: "Ce personnage s'est connecté ailleurs",
	Protocol.E_NO_START_MAP: "Point de départ du monde introuvable",
	Protocol.E_BAD_CELL: "Case invalide",
	Protocol.E_UNREACHABLE: "Impossible d'y aller",
	Protocol.E_NO_EXIT: "Pas de sortie par ici",
	Protocol.E_NO_TARGET: "Cible introuvable",
	Protocol.E_IN_FIGHT: "Impossible en combat",
	Protocol.E_NOT_IN_FIGHT: "Vous n'êtes pas dans ce combat",
	Protocol.E_FIGHT_NOT_STARTED: "Le combat n'a pas commencé",
	Protocol.E_PLACEMENT_OVER: "Le placement est terminé",
	Protocol.E_UNKNOWN_OPTION: "Option de combat inconnue",
	Protocol.E_NOT_LEADER: "Seul le chef de combat peut changer les options",
	Protocol.E_FIGHT_LOCKED: "Le combat est verrouillé",
	Protocol.E_FIGHT_PARTY_ONLY: "Ce combat est réservé au groupe",
	Protocol.E_FIGHT_SECRET: "Ce combat est fermé aux spectateurs",
	Protocol.E_NOT_YOUR_TURN: "Ce n'est pas votre tour",
	Protocol.E_CELL_NOT_FREE: "La case est occupée",
	Protocol.E_UNKNOWN_SPELL: "Sort inconnu",
	Protocol.E_NOT_ENOUGH_AP: "Pas assez de PA",
	Protocol.E_OUT_OF_RANGE: "Hors de portée",
	Protocol.E_NOT_IN_LINE: "Ce sort se lance en ligne",
	Protocol.E_NEEDS_TARGET: "Ce sort nécessite une cible",
	Protocol.E_NO_LOS: "Pas de ligne de vue",
	Protocol.E_SPELL_FORBIDDEN: "Vous ne pouvez pas lancer de sort",
	Protocol.E_SPELL_COOLDOWN: "Sort en recharge",
	Protocol.E_CAST_LIMIT: "Plus de lancers ce tour",
	Protocol.E_CAST_LIMIT_TARGET: "Plus de lancers sur cette cible ce tour",
	Protocol.E_SUMMON_LIMIT: "Nombre maximum d'invocations atteint",
	Protocol.E_SPELL_CONDITION: "Condition du sort non remplie",
	Protocol.E_UNKNOWN_STAT: "Caractéristique inconnue",
	Protocol.E_NOT_ENOUGH_CAPITAL: "Pas assez de points de capital",
	Protocol.E_BAD_NAME: "Nom invalide : une majuscule puis des minuscules, jusqu'à deux tirets (2 à 20 lettres)",
	Protocol.E_NAME_TAKEN: "Ce nom est déjà pris",
	Protocol.E_TOO_MANY_CHARACTERS: "Nombre maximum de personnages atteint sur ce serveur",
	Protocol.E_UNKNOWN_CHARACTER: "Personnage introuvable",
	Protocol.E_CHARACTER_IN_USE: "Ce personnage est en jeu",
	Protocol.E_UNKNOWN_BREED: "Cette classe n'est pas encore disponible",
	Protocol.E_NO_CHARACTER: "Choisissez d'abord un personnage",
	Protocol.E_BAD_LOOK: "Apparence non disponible",
	Protocol.E_SPELL_LOCKED: "Sort pas encore appris",
	Protocol.E_SPELL_NOT_SIMULATED: "Les effets de ce sort ne sont pas encore disponibles",
	Protocol.E_BAD_SLOT: "Emplacement invalide",
	Protocol.E_UNKNOWN_ITEM: "Objet introuvable",
	Protocol.E_ITEM_NOT_USABLE: "Cet objet ne peut pas être utilisé",
	Protocol.E_ITEM_CONDITION: "Conditions d'utilisation non remplies",
	Protocol.E_OVERLOADED: "Vous êtes surchargé : impossible de bouger",
	Protocol.E_ITEM_LEVEL: "Niveau insuffisant pour cet objet",
	Protocol.E_ALREADY_EQUIPPED: "Vous portez déjà cet objet",
	Protocol.E_ITEM_WORN: "Retirez d'abord cet objet",
	Protocol.E_NOT_AT_ZAAP: "Approchez-vous du zaap",
	Protocol.E_UNKNOWN_ZAAP: "Vous ne connaissez pas ce zaap",
	Protocol.E_NOT_ENOUGH_KAMAS: "Vous n'avez pas assez de kamas",
	Protocol.E_GHOST: "Impossible sous forme de fantôme : rejoignez un phénix",
	Protocol.E_NOT_GHOST: "Vous n'êtes pas un fantôme",
	Protocol.E_NOT_AT_PHOENIX: "Approchez-vous du phénix",
	Protocol.E_ENERGY_FULL: "Vos points d'énergie sont déjà au maximum.", # i18n 4691
	Protocol.E_NOT_GM: "Commande réservée aux maîtres du jeu",
	Protocol.E_UNKNOWN_MAP: "Map introuvable",
	Protocol.E_NOT_AT_NPC: "Approchez-vous du personnage",
	Protocol.E_NO_DIALOG: "Ce personnage n'a rien à dire",
	Protocol.E_NO_SHOP: "Cette boutique ne vend pas cela",
	Protocol.E_NO_BANK: "Votre coffre n'est pas ouvert",
	Protocol.E_NOT_SELLABLE: "Ce personnage ne rachète pas cet objet",
	Protocol.E_NO_ELEMENT: "Il n'y a rien à récolter ici",
	Protocol.E_NOT_AT_ELEMENT: "Approchez-vous de la ressource",
	Protocol.E_ELEMENT_BUSY: "Cette ressource n'est pas disponible",
	Protocol.E_JOB_LEVEL: "Niveau de métier insuffisant",
	Protocol.E_NO_CRAFT: "Aucun atelier ouvert",
	Protocol.E_NO_RECIPE: "Ces ingrédients ne font aucune recette",
	Protocol.E_CRAFT_SLOTS: "Trop d'ingrédients pour votre niveau de métier",
	Protocol.E_MISSING_INGREDIENTS: "Il vous manque des ingrédients",
	Protocol.E_FM_ITEM: "Cet objet ne peut pas être forgemagé",
	Protocol.E_FM_RUNE: "Cette rune n'est pas utilisable ici",
	Protocol.E_CHAT_FLOOD: "Vous parlez trop vite",
	Protocol.E_CHANNEL_UNAVAILABLE: "Ce canal n'est pas disponible",
	Protocol.E_PLAYER_OFFLINE: "Ce joueur n'est pas connecté",
	ProtocolParty.E_PARTY_FULL: "Le groupe est complet",
	ProtocolParty.E_ALREADY_IN_PARTY: "Ce joueur est déjà dans un groupe",
	ProtocolParty.E_NOT_IN_PARTY: "Vous n'êtes dans aucun groupe",
	ProtocolParty.E_NOT_PARTY_LEADER: "Seul le chef du groupe peut faire cela",
	ProtocolParty.E_NO_INVITATION: "Cette invitation n'existe plus",
	ProtocolContacts.E_BAD_CONTACT_KIND: "Liste inconnue",
	ProtocolContacts.E_CONTACT_SELF: "Vous ne pouvez pas vous ajouter vous-même",
	ProtocolContacts.E_CONTACT_EXISTS: "Ce joueur est déjà dans cette liste",
	ProtocolContacts.E_CONTACT_FULL: "Cette liste est pleine",
	ProtocolContacts.E_CONTACT_UNKNOWN: "Aucun joueur de ce nom",
	ProtocolTrade.E_TRADE_BUSY: "Vous ne pouvez pas échanger maintenant (échange, combat ou fenêtre déjà ouverte)",
	ProtocolTrade.E_NOT_IN_TRADE: "Aucun échange en cours",
	ProtocolTrade.E_NO_TRADE_INVITATION: "Cette invitation à échanger n'existe plus",
	ProtocolWatch.E_NO_FIGHT: "Ce combat n'existe plus",
	ProtocolWatch.E_FIGHT_FULL: "Ce combat est complet",
	ProtocolWatch.E_FIGHT_STARTED: "Ce combat a déjà commencé",
	ProtocolWatch.E_BAD_TEAM: "Vous ne pouvez pas rejoindre cette équipe",
	ProtocolResume.E_BAD_TOKEN: "La session a expiré : reconnectez-vous",
	ProtocolWatch.E_SPECTATING: "Vous regardez un combat : quittez-le d'abord",
	Protocol.E_FM_RESERVE: "Le puits de l'objet est insuffisant pour dépasser ce maximum",
	Protocol.E_NO_REPLY: "Cette réponse n'est pas possible",
	ProtocolAdmin.E_MUTED: "Vous êtes réduit au silence",
	ProtocolAdmin.E_BANNED: "Ce compte est banni",
	ProtocolAdmin.E_KICKED: "Un maître du jeu vous a expulsé",
	ProtocolSecurity.E_RATE_LIMITED: "Trop de requêtes : ralentissez",
	ProtocolCluster.E_WORLD_CLOSED: "Ce monde vient d'être fermé par un administrateur",
}


static func text(ev: Dictionary) -> String:
	return TEXTS.get(str(ev.get("code", "")), str(ev.get("msg", "Erreur")))
